# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c62456856e0eec1903b27ecb495052ab75be7b1a07eaccf22fe13422bce91a54334a80dda84ea4a95b1a978fadaee6d4bb63a385d7cb16b46230740d23605436

test:
  secret_key_base: f2a8a0f2a0f948395792bc6d4225a118ce86fc62093e13103b652e5d0ee8d5d40ad9f1ea4dfe89f51b53036515323d781c67c8f9fb24c72876fb2dc3239ae1ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
